year: 2023

files:
  concept_mapping:
    data-pipeline-project\230214_concept_codes.csv
  db_query:
    anonymising_data\queries\omop-es\get_data.sql
  output_query:
    anonymising_data\output\get_data.sql