name: Testing

on:
  workflow_dispatch:
  
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Create fake database for linux/macos
      if: matrix.platform != 'windows-latest'
      run: |
       export PYTHONPATH=$PYTHONPATH:$(pwd)
       cd resources/mock-database
       python mock-database.py
       cd ..
       cd ..

    - name: Create fake database for linux/macos
      if: matrix.platform == 'windows-latest'
      run: |
       export PYTHONPATH=$PYTHONPATH:${cd}
       cd resources/mock-database
       python mock-database.py
       cd ..
       cd ..

    - name: Run tests
      run: python -m pytest
